### ISSUE TITLE
Typo in Place struct tag json:"formattedAddressLine"

### ISSUE THREAD

**Issue by saurori** [jweckschmied/applemaps-go#1]
Hey thanks for putting this library together. I noticed there was a typo in the `Place` struct json tag for [FormattedAddressLines](https://github.com/jweckschmied/applemaps-go/blob/v1.0.0/location.go#L25) that results in `place.FormattedAddressLines` always being empty.

The `json` tag should be `json:"formattedAddressLines"` vs `json:"formattedAddressLine"` (missing `s` at end).

**Comment by jweckschmied** [comment]
Thanks @saurori ! I fixed it and released Version v1.0.1
